# Generated by Django 5.2.1 on 2025-05-29 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Vyber kategorii (nepovinné)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='word',
            name='czech',
            field=models.CharField(help_text='Zadej český překlad', max_length=100, verbose_name='Český překlad'),
        ),
        migrations.AlterField(
            model_name='word',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Vyber obtížnost slova', max_length=10, verbose_name='Obtížnost'),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(help_text='Zadej slovo v angličtině (bez speciálních znaků)', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s\\-]+$', 'Pouze písmena, mezery a pomlčky')], verbose_name='Anglické slovo'),
        ),
    ]
