# Generated by Django 5.2.1 on 2025-05-30 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_word_category_alter_word_czech_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameresult',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Výsledek hry', 'verbose_name_plural': 'Výsledky her'},
        ),
        migrations.AddField(
            model_name='gameresult',
            name='duration',
            field=models.DurationField(blank=True, help_text='Jak dlouho hra trvala', null=True, verbose_name='Délka hry'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='mistakes',
            field=models.PositiveIntegerField(default=0, help_text='Kolik chyb udělal hráč', verbose_name='Počet chyb'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='mode',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Zvolená obtížnost hry', max_length=10, verbose_name='Režim hry'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Profil uživatele, který hrál hru', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.userprofile', verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='score',
            field=models.IntegerField(help_text='Počet bodů získaných ve hře', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Skóre'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Kdy byla hra dokončena', verbose_name='Datum a čas'),
        ),
    ]
