# Generated by Django 5.2.1 on 2025-06-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_options_alter_word_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True, help_text='Věta, kde se používá anglické slovo', null=True, verbose_name='Příklad věty'),
        ),
    ]
