# Generated by Django 5.2.4 on 2025-10-04 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_word_example_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(help_text='Zadej slovo v angličtině (bez speciálních znaků)', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s\\-\\(\\)]+$', 'Pouze písmena, mezery, pomlčky a závorky')], verbose_name='Anglické slovo'),
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect_count', models.PositiveIntegerField(default=0, verbose_name='Počet chyb')),
                ('first_incorrect', models.DateTimeField(blank=True, null=True, verbose_name='První chyba')),
                ('last_incorrect', models.DateTimeField(blank=True, null=True, verbose_name='Poslední chyba')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='core.userprofile', verbose_name='Uživatel')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='core.word', verbose_name='Slovo')),
            ],
            options={
                'verbose_name': 'Chyba',
                'verbose_name_plural': 'Chyby',
                'ordering': ['-incorrect_count', '-last_incorrect'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
