# Generated by Django 5.2.4 on 2025-10-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_word_english_mistake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameResult',
        ),
    ]
