# Generated by Django 5.2.1 on 2025-11-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_gameresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Alternativní překlad')),
                ('normalized', models.CharField(db_index=True, editable=False, max_length=120)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_translations', to='core.word')),
            ],
            options={
                'verbose_name': 'Akceptovaná varianta',
                'verbose_name_plural': 'Akceptované varianty',
                'unique_together': {('word', 'normalized')},
            },
        ),
    ]
